### ISSUE TITLE
Drupal Community Publishing

### ISSUE THREAD

**Issue by tgallant** [lilt/tmgmt_lilt#20]
- [x] Create Lilt org
- [x] Create gitlab module repo
- [x] Create documentation
- [x] Submit security review
- [x] Add lilt module link to TMGMT page

**Comment by ShawnConn** [comment]
@tgallant Documentation for the module repo is complete. I added 3 more sections (Installation, Usage, & Development) which I think should cover almost everything a user would need to know for the module. 

I also added some info about the module's tests. Since full test coverage wasn't in spec, I just added a couple of trivial tests so to confirm things are working as they should. 

Please review, if that looks good. I'll mirror the same info on the [module page](https://www.drupal.org/project/tmgmt_lilt).

**Comment by ShawnConn** [comment]
@tgallant: The request for listing the TMGMT Lilt module has been posted: https://www.drupal.org/project/tmgmt/issues/3185936

**Comment by ShawnConn** [comment]
@tgallant: One last test to confirm 1.0 release:

- Create starter D9 site and require `drupal/tmgmt_lilt` project:
```
mkdir test-site
cd test-site
ddev config --project-type=drupal9 --docroot=web --create-docroot
ddev start
ddev composer create "drupal/recommended-project"
ddev composer require drush/drush
ddev composer require 'drupal/tmgmt_lilt:^1.0'
ddev launch
```
- [ ] Confirm that the `tmgmt_lilt` & `tmgmt` modules have been installed in `web/modules/contrib`.
